drop table if exists notification;
drop table if exists report;
drop table if exists person_conference;
drop table if exists conference;
drop table if exists person;



create table if not exists person
(
    id       int generated by default as identity primary key,
    email    varchar not null unique,
    password varchar not null,
    name     varchar not null,
    surname  varchar not null,
    role     int     not null default 0,
    img      bytea,
    blocked  bool    not null default false
);


create table if not exists conference
(
    id          int generated by default as identity primary key,
    title       varchar not null unique,
    date        date    not null,
    location    varchar not null,
    description varchar not null,
    img         bytea,
    visitors    int default 0,
    places      int     not null
);

create table if not exists person_conference
(
    person_id     int not null references person (id) on delete cascade on update cascade,
    conference_id int not null references conference (id) on delete cascade on update cascade,
    primary key (person_id, conference_id)
);



create table if not exists report
(
    id            int generated by default as identity primary key,
    topic         varchar not null unique,
    description   varchar not null,
    materials     bytea,
    status        int     not null default 0,
    conference_id int     not null references conference (id) on delete cascade on update cascade,
    person_id     int references person (id)
);

create table if not exists notification
(
    id          int generated by default as identity primary key,
    message     varchar not null,
    read_status bool default false,
    person_id   int     not null references person (id) on delete cascade on update cascade
);
